### ISSUE TITLE
bin/sh: love: command not found  on OSX 

### ISSUE THREAD

**Issue by TakWolf** [rameshvarun/love-ide#11]
when click the tool-bar run button on osx.

On windows，i have  'love.exe' in %PATH% and everything work fine.

how can i do config with osx?

##
i have a love.app in  

    "/Applications/love.app"

and i have config a alias for love like this in .bash_profile

    alias love="/Applications/love.app/Contents/MacOS/love"

i can call love command in console.

**Comment by TakWolf** [comment]
atom gave me a issue link : 

https://github.com/atom/atom/issues/8937

https://github.com/atom/atom/issues/8937#issuecomment-143325006

**Comment by rameshvarun** [comment]
Your best bet is to go to the `love-ide` settings menu. From there, you can specify the full path to the LOVE executable. This menu can be opened with Packages > Settings View > Open.

Other than that, it should also work if `"/Applications/love.app/Contents/MacOS/love"` is added to the PATH environment variable ([guide](http://architectryan.com/2012/10/02/add-to-the-path-on-mac-os-x-mountain-lion/)) - aliases will not work.

**Comment by TakWolf** [comment]
It is work, thinks very much!!!
This is the best working environment I have found!
