### ISSUE TITLE
Any way to see terminal output?

### ISSUE THREAD

**Issue by jamesaspence** [rameshvarun/love-ide#13]
Just discovered this package. I like it. However, is there a way for me to see my terminal output while running the game? If I run Love through terminal, I can then see my printed output there. I see nothing of the like here, however.

**Comment by rameshvarun** [comment]
What platform are you on? I see two ways of implementing this feature.

One possible way is [term3](https://github.com/Floobits/atom-term3), which has a service API for creating and manipulating `TermView`s. Using this, you would also be able to interact with the process. Unfortunately, term3 only works on OSX/Linux - not Windows.

Another option is to integrate into [build](https://atom.io/packages/build), which has it's own window.

**Comment by jamesaspence** [comment]
I am using OSX, but I'm pretty tied to my current terminal (iTerm 2). Most of the time I just end up running through terminal instead of through the IDE.

**Comment by rameshvarun** [comment]
Fixed by 5a4436f5f9f1d3bd70cf75638a7e9c54b52fe56d

To use this, go into the `love-ide` package settings and set the Terminal Emulator option to `iTerm2`.
