### ISSUE TITLE
t.console = true doesnt work with play button

### ISSUE THREAD

**Issue by tgrehawi** [rameshvarun/love-ide#15]
launching love through the toolbar play button does not open a console with t.console = true on windows (love.conf)

**Comment by WarlockD** [comment]
Also if you add --console to the arguments it doesn't launch either.  I tried making a bat file and changing where --console is run but it still didn't fix it

**Comment by rameshvarun** [comment]
I've just added a terminal emulator option in the settings. Switch it to the `CMD (Windows)` option, and you should get the console when you run.
