### ISSUE TITLE
Broken Packages

### ISSUE THREAD

**Issue by Meryl-nj** [rameshvarun/love-ide#21]
Can't install hyperclick and autocomplete.

**Comment by Avalium** [comment]
I'm getting this issue as well, did this ever get resolved?

**Comment by rameshvarun** [comment]
I recently reset my computer, and the installer seems to work for me on OSX. What OS are you on?
Does it work if you install the packages individually?

**Comment by Avalium** [comment]
Installing them individually seems to have worked.

**Comment by pbondoer** [comment]
Can confirm the same is happening here on Windows. The issue seems to be atom is cloning the git repositories from https and most Windows git versions do not seem to support it well.

Stack trace:
```
C:\Users\lemon\.atom\packages\love-ide\node_modules\atom-package-deps\lib\view.js:65 [Package-Deps] Unable to install hyperclick-love, Error: npm ERR! git fetch -a origin (https://github.com/rameshvarun/love-ide-data.git) fatal: Unable to find remote helper for 'https'
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Users\\lemon\\AppData\\Local\\atom\\app-1.15.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\lemon\\AppData\\Local\\atom\\app-1.15.0\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\lemon\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\lemon\\.atom\\.apmrc" "install" "C:\\Users\\lemon\\AppData\\Local\\Temp\\d-117229-8644-1fc15ks\\package.tgz" "--runtime=electron" "--target=1.3.13" "--arch=x64" "--global-style" "--production"
npm ERR! node v4.4.5
npm ERR! npm  v3.10.5
npm ERR! code 128

npm ERR! Command failed: git -c core.longpaths=true fetch -a origin
npm ERR! fatal: Unable to find remote helper for 'https'
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\lemon\AppData\Local\Temp\apm-install-dir-117229-8644-nzlhut\npm-debug.log
```

**Comment by rameshvarun** [comment]
I think this is fixed, so I'm tentatively closing this issue. It looks like there were problems with both https and submodules on Windows, though I have no idea why it only seems to show up during the auto-install. 

Either way, I've bypassed the issue entirely since `autocomplete-love` and `hyperclick-love` now download the API data as a tarball, which I think is better anyways since the sub-modules are only necessary for generating the data.
