### ISSUE TITLE
"run-love" shotcut

### ISSUE THREAD

**Issue by Winterwolf** [rameshvarun/love-ide#25]
Hello. I trying to create custom shotcut for "run-love" command and it's not working:

```
'love-ide':
  'f5': 'love-ide:run-love'
```
this not working too:

```
'love-ide':
  'f5': 'run-love'
```

**Comment by Winterwolf** [comment]
Looks like keybinding is added, but F5 not react.

![Screenshot](http://i.imgur.com/8weiIBT.png)

**Comment by Nikaoto** [comment]
@Winterwolf 
Something may be wrong with your editor, it's working perfectly for me. In my **keymap.cson** file I added:
```
'atom-text-editor':
    'f5' : 'love-ide:run-love'
```

and it runs without any problems.

**Comment by Winterwolf** [comment]
Thank you. With 'atom-text-editor' it works.
