### ISSUE TITLE
Can't see "Run Love App" button

### ISSUE THREAD

**Issue by MilkBomb11** [rameshvarun/love-ide#33]
After updating Run Icon in the Toolbar, it vanished.
The toolbar is still displayed and the button is highlighted when I hover my mouse over where it was, but the white triangle is gone.

**Comment by kreato** [comment]
Hi @MilkBomb11,
The icon set love-ide is using is Ionicons. It is stated here https://github.com/suda/tool-bar#supported-icon-sets that the icons for this set should be prefixed with "ios"- or "md-".

You can see in the source code in lib/main.js on row 150 that the icon is "play". It should be prefixed with one of the mentioned prefixes.

A temporary quick fix is to go to your atom packages (I'm running Ubuntu and in my case, the path is ~/.atom/packages), find the love-ide package, open the main.js file with an editor and edit the row 150: icon: 'ios-play'. Restart atom and you will see the icon. 

This is in case you don't want to wait for the developer to fix it.

@rameshvarun FYI

**Comment by Rualani** [comment]
Can confirm that this was the issue when I was using it. Adding "md-" fixed it.

**Comment by hellobetkowski** [comment]
Added 'ios-' on line 150 in main.js file, just like @kreato,
can confirm it works on macOS Catlina.

**Comment by Beezlede** [comment]
To make the main.js easier to find:
In Atom open 'Settings' or 'Preferences' -> 'Packages'. Then search for the 'love-ide' package. Click on 'View Code'.
Go to the lib/main.js file and edit line 150.

**Comment by MilkBomb11** [comment]
Adding "md-" or "ios-" before "play" in line 150 of main.js of source code solved the problem!
Thanks for the help!
