### ISSUE TITLE
Toolbar Love Icon

### ISSUE THREAD

**Issue by acz13** [rameshvarun/love-ide#6]
I happen to use the Run icon for something else. Is it possible to use a Love2d icon instead on the toolbar?

**Comment by rameshvarun** [comment]
That sounds like a good idea - I've noticed that other packages are using the run icon as well, so it would be a good idea to avoid conflicts. Unfortunately, the tool-bar package doesn't support custom icons right now, so we will have to wait for https://github.com/suda/tool-bar/issues/48.

One thing that can be added is to have the button disappear and reappear based off whether the current project is a Love2D game. Would that resolve the conflict in your case?

**Comment by ciw1973** [comment]
Ideally I'd like to be able to turn it off completely, as I don't use the toolbar for anything else, and it's taking up valuable screen space. A command which could be bound to a key combination would then be good.
